
```{r}
setwd("~/Documents/GitHub/My-repo/My-repo/data")
e12.e11 = read.csv("e12_e11_all_de_tf.csv", stringsAsFactors = FALSE)
e13.e12 = read.csv("e13_e12_all_de_tf.csv", stringsAsFactors = FALSE)
e14.e13 = read.csv("e14_e13_all_de_tf.csv", stringsAsFactors = FALSE)
e13.e11 = read.csv("e13_e11_all_de_tf.csv", stringsAsFactors = FALSE)
e14.e11 = read.csv("e14_e11_all_de_tf.csv", stringsAsFactors = FALSE)
e14.e12 = read.csv("e14_e12_all_de_tf.csv", stringsAsFactors = FALSE)
```


```{r}

e12.e11 = subset(e12.e11, abs(e12.e11$log2FoldChange)>=1)[,c(9,3)]
e13.e12 = subset(e13.e12, abs(e13.e12$log2FoldChange)>=1)[,c(9,3)]
e14.e13 = subset(e14.e13, abs(e14.e13$log2FoldChange)>=1)[,c(9,3)]
e13.e11 = subset(e13.e11, abs(e13.e11$log2FoldChange)>=1)[,c(9,3)]
e14.e11 = subset(e14.e11, abs(e14.e11$log2FoldChange)>=1)[,c(9,3)]
e14.e12 = subset(e14.e12, abs(e14.e12$log2FoldChange)>=1)[,c(9,3)]

```

```{r}
merged = merge(e12.e11, e13.e12, by = "Symbol", all = TRUE)
merged = merge(merged, e14.e13, by = "Symbol", all = TRUE)
merged = merge(merged, e13.e11, by = "Symbol", all = TRUE)
merged = merge(merged, e14.e11, by = "Symbol", all = TRUE)
merged = merge(merged, e14.e12, by = "Symbol", all = TRUE)


```



```{r}
setwd("~/Documents/GitHub/My-repo/My-repo/data")
data = read.csv("corrected gene count matrix.txt", row.names = 1, stringsAsFactors = FALSE)[,1:23]
head(data)
```

```{r}
setwd("~/Documents/GitHub/My-repo/My-repo/data")
tf = read.csv("all de tf 0.5 cutoff btw any time points.csv", stringsAsFactors = FALSE, row.names = 1)
head(tf)
```

```{r}
tf = merged$Symbol
```

```{r}
tf_count_matrix = data[tf,]
```


Use DESeq2 to normalize the data
```{r}
library(DESeq2)
library(ggplot2)
library(pheatmap)
library(RColorBrewer)
```

```{r}
stage = c(rep("E11", 5), rep("E12", 7), rep("E13", 7), rep("E14", 4))
design = data.frame(stage)
row.names(design) = colnames(data)
```

```{r}
dds = DESeqDataSetFromMatrix(countData = tf_count_matrix,
                             colData = design,
                             design = ~stage)
```

Filter out low count genes
```{r}
dds_filtered = dds[rowSums(counts(dds))>1000,]

```


```{r}
rld = rlog(dds_filtered, blind = FALSE)
logTransCounts = assay(rld)
```

```{r}
setwd("~/Documents/GitHub/My-repo/My-repo/Graphs")
png("heatmap of transcription factors log transform v1.png", width = 1000, height = 5000, units = "px")
pheatmap(logTransCounts, cluster_cols = F, treeheight_row = 0, treeheight_col = 0, color = colorRampPalette(rev(brewer.pal(10, "RdYlGn")))(30))
dev.off()
```

```{r}
converted = data.frame(logTransCounts)
```

```{r}
delta_max_min = c()
for(i in 1:255){
  delta = max(converted[i, 1:23]) - min(converted[i, 1:23])
  delta_max_min = c(delta_max_min, delta)
}
```

```{r}
converted$delta_max_min = delta_max_min
head(converted)
```

```{r}
min = c()
for(i in 1:255){
  min_value = min(converted[i, 1:23])
  min = c(min, min_value)
}
```

```{r}
converted$min = min
```

```{r}
converted$e11.sample1 = (converted$e11.sample1 - converted$min)/converted$delta_max_min

converted$e11.sample2 = (converted$e11.sample2 - converted$min)/converted$delta_max_min

converted$e11.sample3 = (converted$e11.sample3 - converted$min)/converted$delta_max_min

converted$e11.sample4 = (converted$e11.sample4 - converted$min)/converted$delta_max_min

converted$e11.sample5 = (converted$e11.sample5 - converted$min)/converted$delta_max_min

converted$e12.sample1 = (converted$e12.sample1 - converted$min)/converted$delta_max_min

converted$e12.sample2 = (converted$e12.sample2 - converted$min)/converted$delta_max_min

converted$e12.sample3 = (converted$e12.sample3 - converted$min)/converted$delta_max_min

converted$e12.sample4 = (converted$e12.sample4 - converted$min)/converted$delta_max_min

converted$e12.sample5 = (converted$e12.sample5 - converted$min)/converted$delta_max_min

converted$e12.sample6 = (converted$e12.sample6 - converted$min)/converted$delta_max_min

converted$e12.sample7 = (converted$e12.sample7 - converted$min)/converted$delta_max_min

converted$e13.sample1 = (converted$e13.sample1 - converted$min)/converted$delta_max_min

converted$e13.sample2 = (converted$e13.sample2 - converted$min)/converted$delta_max_min

converted$e13.sample3 = (converted$e13.sample3 - converted$min)/converted$delta_max_min

converted$e13.sample4 = (converted$e13.sample4 - converted$min)/converted$delta_max_min

converted$e13.sample5 = (converted$e13.sample5 - converted$min)/converted$delta_max_min

converted$e13.sample6 = (converted$e13.sample6 - converted$min)/converted$delta_max_min

converted$e13.sample7 = (converted$e13.sample7 - converted$min)/converted$delta_max_min

converted$e14.sample1 = (converted$e14.sample1 - converted$min)/converted$delta_max_min

converted$e14.sample2 = (converted$e14.sample2 - converted$min)/converted$delta_max_min

converted$e14.sample3 = (converted$e14.sample3 - converted$min)/converted$delta_max_min

converted$e14.sample4 = (converted$e14.sample4 - converted$min)/converted$delta_max_min

#converted$e14.sample5 = (converted$e14.sample5 - converted$min)/converted$delta_max_min

```


```{r}
setwd("~/Documents/GitHub/My-repo/My-repo/data")
write.csv(converted[,1:23], "converted read counts for tf.csv")
```


```{r}
library(RColorBrewer)
```

```{r}
library(tidyverse)
library(cluster)
library(factoextra)
```

```{r}
k4 = kmeans(converted[,1:23], centers = 4, nstart = 100)
```

```{r}
k3 = kmeans(converted[,1:23], centers = 3, nstart = 100)
```

```{r}
dataframe = converted[,1:23]
dataframe$cluster = k3$cluster
```

```{r}
dataframe_order = dataframe[order(dataframe$cluster),]
```

```{r}
setwd("~/Documents/GitHub/My-repo/My-repo/data")
mus_tf = read.csv("Mus_musculus_TF.txt", sep = "\t")
head(mus_tf)
```

```{r}
tf_fam = mus_tf[mus_tf$Symbol %in% row.names(dataframe_order) , ]
tf_fam = tf_fam[order(tf_fam$Symbol),]
```

```{r}
row.names(tf_fam) = c(1:257)
```

```{r}
tf_fam = tf_fam[-54, ]
```

```{r}
tf_fam = tf_fam[-70, ]
```

```{r}
row.names(tf_fam) = tf_fam$Symbol
```

```{r}
dataframe_order$Family = tf_fam[row.names(dataframe_order),]$Family
```

```{r}
setwd("~/Desktop/My-repo/data")
write.csv(dataframe_order, "SSTF with cluster.csv")
```

```{r}
library(pheatmap)
library(RColorBrewer)
```

 
```{r}
setwd("~/Documents/GitHub/My-repo/My-repo/Graphs")
png("heatmap of transcription factors relative expression v3.png", width = 1000, height = 5000, units = "px")
pheatmap(dataframe_order[,1:23], cluster_cols = F, cluster_rows = F, treeheight_row = 0, treeheight_col = 0, color = colorRampPalette(rev(brewer.pal(10, "RdYlGn")))(30))
dev.off()
```


```{r}
setwd("~/Desktop/My-repo/data")
dataframe_order = read.csv("SSTF with cluster.csv", row.names = 1, stringsAsFactors = FALSE)

```

Plot individual map for each cluster

```{r}
cluster_1 = dataframe_order[dataframe_order$cluster==1, c(1:23,25)]
```


```{r}
setwd("~/Desktop/My-repo/data")
write.csv(cluster_1, "cluster 1.csv")
```

```{r}
setwd("~/Desktop/My-repo/Graphs")
png("cluster 1.png", width = 1000, height = 5000, units = "px")
pheatmap(cluster_1[,1:23], cluster_cols = F, cluster_rows = F, fontsize = 40,fontsize_row = 40, treeheight_row = 0, treeheight_col = 0, color = colorRampPalette(rev(brewer.pal(10, "RdYlGn")))(30))
dev.off()
```

```{r}
cluster_2 = dataframe_order[dataframe_order$cluster==2, c(1:23,25)]
```


```{r}
setwd("~/Desktop/My-repo/data")
write.csv(cluster_2, "cluster 2.csv")
```

```{r}
setwd("~/Desktop/My-repo/Graphs")
png("cluster 2.png", width = 1000, height = 3695, units = "px")
pheatmap(cluster_2[,1:23], cluster_cols = F, cluster_rows = F, fontsize = 40,fontsize_row = 40, treeheight_row = 0, treeheight_col = 0, color = colorRampPalette(rev(brewer.pal(10, "RdYlGn")))(30))
dev.off()
```
```{r}
cluster_3 = dataframe_order[dataframe_order$cluster==3, c(1:23,25)]
```


```{r}
setwd("~/Desktop/My-repo/data")
write.csv(cluster_3, "cluster 3.csv")
```

```{r}
setwd("~/Desktop/My-repo/Graphs")
png("cluster 3.png", width = 1000, height = 2400, units = "px")
pheatmap(cluster_3[,1:23], cluster_cols = F, cluster_rows = F, fontsize = 40,fontsize_row = 40, treeheight_row = 0, treeheight_col = 0, color = colorRampPalette(rev(brewer.pal(10, "RdYlGn")))(30))
dev.off()
```




```{r}
setwd("~/Desktop/My-repo/Graphs")
png("all tf.png", width = 3000, height = 20000, units = "px")
pheatmap(dataframe_order[,1:23], cluster_cols = F, cluster_rows = F, fontsize = 70,fontsize_row = 70, treeheight_row = 0, treeheight_col = 0, color = colorRampPalette(rev(brewer.pal(10, "RdYlGn")))(30))
dev.off()
```
